### ISSUE TITLE
Move to Stampie organization

### ISSUE THREAD

**Issue by Nyholm** [Stampie/extra#3]
May I be so forward and ask you to move this lib to the Stampie organization?

**Comment by stof** [comment]
Will do next week, together with the work on the update to 1.0 and the renaming

**Comment by Nyholm** [comment]
Perfect. Thanks!

**Comment by Nyholm** [comment]
A friendly reminder.

**Comment by fbourigault** [comment]
I sent two PRs to update the lib with 1.0. If you are too busy to review those, could you move the repo in the Stampie org, we (Tobias and I) will do all required work in the Stampie org.
